Header header # Obvious

float64 x_m                       # X position in meters, local frame
float64 y_m                       # Y position in meters, local frame
float64 longitudinal_velocity_mps # Longitudinal velocity in mps
float64 lateral_velocity_mps      # Lateral velocity in mps
float64 heading_r                 # Heading in radians, local frame
float64 yaw_rate_rps              # Yaw rate in radians per second
float64 max_speed_mps             # Max speed in mps
float64 max_accel_mpss            # Max acceleration in mpss